export const SET_ALL_COMMENT = "SET_ALL_COMMENT";
export const SET_COMMENT = "SET_COMMENT";
export const SET_COMMENT_USER_NAME = "SET_COMMENT_USER_NAME";
export const SET_COMMENT_USER_IMG = "SET_COMMENT_USER_IMG";
export const RESET_COMMENT = "RESET_COMMENT";
